name: TNPSC Bot Monitor

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch: # 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # v3-க்கு பதிலாக v4

      - name: Set up Python
        uses: actions/setup-python@v5  # v4-க்கு பதிலாக v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
